repos:
  # Adding custom cleaning utility
  - repo: local
    hooks:
      - id: clean-directory
        name: clean directory
        entry: >
          bash -c 'clean() {
            local directory="$1";
            if [ ! -d "$directory" ]; then
              echo "Directory '\''$directory'\'' not found";
              return;
            fi;
            find "$directory" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null;
            find "$directory" -type f -name ".DS_Store" -exec rm -f {} + 2>/dev/null;
            find "$directory" -type d -name "catboost_info" -exec rm -r {} + 2>/dev/null;
            find "$directory" -type d -name ".ruff_cache" -exec rm -r {} + 2>/dev/null;
            find "$directory" -type d -name ".ipynb_checkpoints" -exec rm -r {} + 2>/dev/null;
          }; clean .'
        language: system
        always_run: true
  # # Adding Pycln
  # - repo: https://github.com/hadialqattan/pycln
  #   rev: 'v2.1.5'
  #   hooks:
  #   -   id: pycln
  #       args: ['.']
  # Adding Pip-compile
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile
  # Adding Autoflake
  - repo: https://github.com/myint/autoflake
    rev: v1.4  # Use the most recent revision
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--ignore-init-module-imports"]
  # Adding PreCommit Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending
  # Adding Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
      - id: black-jupyter
  # Adding Isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  # # Adding mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.942
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-requests
  #       args:
  #         - --ignore-missing-imports

  # ====================  Security Hooks  ====================
  # # Adding Bandit
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.4  # Use the most recent revision
  #   hooks:
  #     - id: bandit
  # # Adding Safety
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.2.1  # Use the most recent revision
  #   hooks:
  #     - id: safety
  #       args: [--full-report]

  # ====================  Testing Hooks  ====================
  # # Adding Pytest
  # - repo: local
  #   hooks:
  #   - id: pytest
  #     name: pytest
  #     entry: pytest
  #     language: system
  #     pass_filenames: false
  # # Adding UnitTest
  # - repo: local
  #   hooks:
  #   - id: unittest
  #     name: unittest
  #     entry: python -m unittest discover
  #     language: system
  #     pass_filenames: false
  # # Adding Pytest-cov
  # - repo: local
  #   hooks:
  #   - id: pytest-cov
  #     name: pytest with coverage
  #     entry: pytest --cov=<your_package_name>
  #     language: system
  #     pass_filenames: false

  # ====================  Formatting Hooks  ====================
  # # Adding Prettier
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v2.3.2"  # Use the most recent revision
  #   hooks:
  #     - id: prettier
  # # Adding Check-docstring-first
  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.9.0  # Use the most recent revision
  #   hooks:
  #     - id: python-check-blanket-noqa
  #       args: [--multiline]
  # # Adding Autopep8
  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: v2.0.2
  #   hooks:
  #     - id: autopep8
  # # Adding Flake8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-bugbear
  #         - flake8-comprehensions
  #         - flake8-simplify
  #       types: [python]
  #       files: ^(?!\.venv|venv|env|migration).*\.py$
  #       args: [--extend-ignore=B950]

  # ====================  Documenting Hooks  ====================
  # # Adding Check-manifest
  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: 0.48  # Use the most recent revision
  #   hooks:
  #     - id: check-manifest
